- name: packer-oracle-database assistant
  hosts: 127.0.0.1

  vars:
    var_file: oracle-database-11g-ol7.json

  vars_prompt:
    - name: "database_edition"
      prompt: "oracle database edition ('ee' or 'se')"
      default: "se"

  tasks:

    - shell: "ansible-galaxy install -f -p roles -r roles.yml"

    - copy:
        src: "{{ item }}"
        dest: roles/oracle-database/files/
        force: no
      with_items:
        - "{{ ansible_env.HOME }}/oracle/database/installers/11.2.0.4/oracle_database-11.2.0.4-1of2.zip"
        - "{{ ansible_env.HOME }}/oracle/database/installers/11.2.0.4/oracle_database-11.2.0.4-2of2.zip"

    - shell: "packer build -var-file=oracle-database-11g-{{ database_edition }}-ol7.json -force=true oracle-database.json > build.log"
