---
- name: oracle database 11g (11.2.0.4)
  hosts: 127.0.0.1

  roles:
    - role: nfs
      nfs_mode: client
      nfs_client_imports:
        -
          local: /srv/files
          remote: /installers/oracle/db/11.2/database/11.2.0.4
          server_host: 52.21.104.103
    - role: oracle-database
      oracle_database_version: 11g
      oracle_database_edition: SE
      oracle_database_installer_directory: /srv/files/database
