---
  - template: src=templates/dbca.rsp.j2 dest=/tmp/dbca.rsp
    become: yes
    become_user: "oracle"
  - name: Create Instance
    command: "$ORACLE_HOME/bin/dbca -silent -responseFile /tmp/dbca.rsp"
    become: yes
    become_user: "oracle"
    args:
      creates: "{{ oracle_home }}/dbs/spfile{{ db_sid }}.ora"
    register: command_result
    failed_when: "'100% complete' not in command_result.stdout_lines"

  - name: Generate Start Server Upstart Script
    template: src=templates/oradb.conf.j2 dest=/etc/init/oradb.conf
  - name: Enable Service
    service: name=oradb enabled=yes
  #- name: Setting Environmental Variables
  #  template: src=templates/bash_profile.j2 dest=/home/{{ db_user }}/.bash_profile
  #  become: yes
  #  become_user: "{{ db_user }}"
  - name: Setting Environmental Variables
    template: src=templates/oratab.j2 dest=/etc/oratab owner={{ db_user }} group={{ db_install_group }}
